class ButtonText:
    UPLOAD = "Загрузить фото"
    MY_FILES = "Мои фото"
    EDIT_NAME = "Изменить название"
    DELETE_FOLDER = "Удалить"
    CANCEL = "Отмена"
    YES = "Да"
    NO = "Нет"
    GET_TELEGRAM_ID = "Узнать Telegram ID"
    SELECT_FACE = "Указать лицо"
    SKIP = "Пропустить"
